### ISSUE TITLE
Add support for GSI OpenSSH

### ISSUE THREAD

**Issue by billglick** [ncsa/puppet-sshd#12]
See https://opensciencegrid.org/docs/other/gsissh/

If we include full gsissh support into this module it will require:
- optional configuration for `gsissh`
- additional packages
- alternate sshd service
- build gridmap files, etc
- alternate sshd_config authentication settings
- obtaining a host certificate

Optionally, just need to add the optional ability to NOT manage the sshd service, and create unique module/profile for `gsissh`.

**Comment by billglick** [comment]
See the following tickets for the request for this feature:

- https://jira.ncsa.illinois.edu/browse/DELTA-198?focusedCommentId=491726&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-491726
- https://jira.ncsa.illinois.edu/browse/SVC-16496

**Comment by andylytical** [comment]
If gsi_ssh is written as it's own module:

- Could/would these have to work together?
- If not working together, what functionality get's duplicated between the two modules?

Any duplicated work means doubled maintenance ... any fix that affects a duplicated part must be implemented in both places.

**Comment by billglick** [comment]
I do not think there is any functionality duplication. `ncsa/sshd` would still be used for configuring `sshd_config` etc. gsi-openssh config files are unique, but just end up being symlinks to the traditional openssh configs. 

The main catch is that the openssh sshd service needs to not be running if gsi-openssh sshd is instead running on port 22.
